export const dummyTranscations = [
  {
    path: '0.jpg',
    sender: 'James Thompson',
    category: 'dinning out',
    date: new Date('2023-06-15'),
    amount: '+' + 75,
  },
  {
    path: '1.jpg',
    sender: 'Pixel Playground ',
    category: 'entertainment',
    date: new Date('2024-05-15'),
    amount: '+' + 200,
  },
  {
    path: '2.jpg',
    sender: 'Ethan Clark',
    category: 'bills',
    date: new Date('2020-06-18'),
    amount: '+' + 450,
  },
  {
    path: '3.jpg',
    sender: 'hany elsaied',
    category: 'grocires',
    date: new Date('2023-06-15'),
    amount: '+' + 56,
  },
  {
    path: '4.jpg',
    sender: 'elmahmoudy emad',
    category: 'grocires',
    date: new Date('2022-04-10'),
    amount: '+' + 47,
  },
  {
    path: '5.jpg',
    sender: 'dr.mamdouh nasrallah',
    category: 'grocires',
    date: new Date('2024-08-10'),
    amount: '+' + 26,
  },
  {
    path: '6.jpg',
    sender: 'Liam Hughes',
    category: 'dinning out',
    date: new Date('2022-06-10'),
    amount: '+' + 100,
  },
  {
    path: '7.jpg',
    sender: 'Emma Richardson',
    category: 'transportation',
    date: new Date('2021-04-16'),
    amount: '+' + 40,
  },

  {
    path: '8.jpg',
    sender: 'ahmed amr',
    category: 'personal care',
    date: new Date('2023-06-10'),
    amount: '+' + 150,
  },

  {
    path: '9.jpg',
    sender: 'Hanna ammar',
    category: 'personal care',
    date: new Date('2023-09-17'),
    amount: '+' + 423,
  },
  {
    path: '10.jpg',
    sender: 'mona saeed',
    category: 'personal care',
    date: new Date('2022-07-12'),
    amount: '+' + 150,
  },
  {
    path: '11.jpg',
    sender: 'Ismael isaak',
    category: 'education',
    date: new Date('2023-06-15'),
    amount: '+' + 250,
  },
  {
    path: '12.jpg',
    sender: 'ramy sabry',
    category: 'lifestyle',
    date: new Date('2025-01-17'),
    amount: '+' + 100,
  },
  {
    path: '13.jpg',
    sender: 'khaled selim',
    category: 'shopping',
    date: new Date('2023-06-15'),
    amount: '+' + 110,
  },
  {
    path: '14.jpg',
    sender: 'ahmed badran',
    category: 'general',
    date: new Date('2023-06-15'),
    amount: '+' + 112,
  },
  {
    path: '15.jpg',
    sender: 'yunes shelpy',
    category: 'shopping',
    date: new Date('2023-06-15'),
    amount: '+' + 143,
  },
  {
    path: '16.jpg',
    sender: 'tomas tyler',
    category: 'shopping',
    date: new Date('2023-06-15'),
    amount: '+' + 154,
  },
  {
    path: '',
    sender: 'Hanaa elhussany',
    category: 'shopping',
    date: new Date('2023-06-15'),
    amount: '+' + 166,
  },
  {
    path: '',
    sender: 'tahany ammar',
    category: 'dinning out',
    date: new Date('2023-06-15'),
    amount: '+' + 179,
  },
  {
    path: '',
    sender: 'nema mohamed Hassan',
    category: 'entertainment',
    date: new Date('2023-06-15'),
    amount: '+' + 145,
  },
  {
    path: '',
    sender: 'Nadia galal Aly ',
    category: 'entertainment',
    date: new Date('2023-06-15'),
    amount: '+' + 136,
  },
  {
    path: '',
    sender: 'amal abd el Elrhmany',
    category: 'transportation',
    date: new Date('2023-06-15'),
    amount: '+' + 145,
  },
  {
    path: '',
    sender: 'Jason blade',
    category: 'transportation',
    date: new Date('2023-06-15'),
    amount: '+' + 280,
  },
  {
    path: '',
    sender: 'anna',
    category: 'transportation',
    date: new Date('2023-06-15'),
    amount: '+' + 200,
  },
  {
    path: '',
    sender: 'donia ammar',
    category: 'education',
    date: new Date('2023-06-15'),
    amount: '+' + 650,
  },
  {
    path: '',
    sender: 'Hany elsaeed',
    category: 'bills',
    date: new Date('2023-06-15'),
    amount: '+' + 90,
  },
  {
    path: '',
    sender: 'ahmed santa',
    category: 'bills',
    date: new Date('2023-06-15'),
    amount: '+' + 70,
  },
  {
    path: '',
    sender: 'ahmed amr',
    category: 'bills',
    date: new Date('2023-06-15'),
    amount: '+' + 660,
  },
];

/***
 * import { page } from './transactions.model';

export const dummyTranscations: page[] = [
  {
    current_page: 1,
    page_data: [
      {
        path: '',
        sender: 'James Thompson',
        category: 'dinning out',
        date: new Date('2023-06-15'),
        amount:'+'+ 75,
      },
      {
        path: '',
        sender: 'Pixel Playground ',
        category: 'entertainment',
        date: new Date('2024-05-15'),
        amount:'+'+ 200,
      },
      {
        path: '',
        sender: 'Ethan Clark',
        category: 'bills',
        date: new Date('2020-06-18'),
        amount:'+'+ 450,
      },
      {
        path: '',
        sender: 'hany elsaied',
        category: 'grocires',
        date: new Date('2023-06-15'),
        amount:'+'+ 56,
      },
      {
        path: '',
        sender: 'elmahmoudy emad',
        category: 'grocires',
        date: new Date('2022-04-10'),
        amount:'+'+ 47,
      },
      {
        path: '',
        sender: 'dr.mamdouh nasrallah',
        category: 'grocires',
        date: new Date('2024-08-10'),
        amount:'+'+ 26,
      },
      {
        path: '',
        sender: 'Liam Hughes',
        category: 'dinning out',
        date: new Date('2022-06-10'),
        amount:'+'+ 100,
      },
      {
        path: '',
        sender: 'Emma Richardson',
        category: 'transportation',
        date: new Date('2021-04-16'),
        amount:'+'+ 40,
      },

      {
        path: '',
        sender: 'ahmed amr',
        category: 'personal care',
        date: new Date('2023-06-10'),
        amount:'+'+ 150,
      },

      {
        path: '',
        sender: 'Hanna ammar',
        category: 'personal care',
        date: new Date('2023-09-17'),
        amount:'+'+ 423,
      },
    ],
  },
  {
    current_page: 2,
    page_data: [
      {
        path: '',
        sender: 'mona saeed',
        category: 'personal care',
        date: new Date('2022-07-12'),
        amount:'+'+ 150,
      },
      {
        path: '',
        sender: 'Ismael isaak',
        category: 'education',
        date: new Date('2023-06-15'),
        amount:'+'+ 250,
      },
      {
        path: '',
        sender: 'ramy sabry',
        category: 'lifestyle',
        date: new Date('2025-01-17'),
        amount:'+'+ 100,
      },
      {
        path: '',
        sender: 'khaled selim',
        category: 'shopping',
        date: new Date('2023-06-15'),
        amount:'+'+ 110,
      },
      {
        path: '',
        sender: 'ahmed badran',
        category: 'general',
        date: new Date('2023-06-15'),
        amount:'+'+ 112,
      },
      {
        path: '',
        sender: 'yunes shelpy',
        category: 'shopping',
        date: new Date('2023-06-15'),
        amount:'+'+ 143,
      },
      {
        path: '',
        sender: 'tomas tyler',
        category: 'shopping',
        date: new Date('2023-06-15'),
        amount:'+'+ 154,
      },
      {
        path: '',
        sender: 'Hanaa elhussany',
        category: 'shopping',
        date: new Date('2023-06-15'),
        amount:'+'+ 166,
      },
      {
        path: '',
        sender: 'tahany ammar',
        category: 'dinning out',
        date: new Date('2023-06-15'),
        amount:'+'+ 179,
      },
      {
        path: '',
        sender: 'nema mohamed Hassan',
        category: 'entertainment',
        date: new Date('2023-06-15'),
        amount:'+'+ 145,
      },
    ],
  },
  {
    current_page: 3,
    page_data: [
      {
        path: '',
        sender: 'Nadia galal Aly ',
        category: 'entertainment',
        date: new Date('2023-06-15'),
        amount:'+'+ 136,
      },
      {
        path: '',
        sender: 'amal abd el Elrhmany',
        category: 'transportation',
        date: new Date('2023-06-15'),
        amount:'+'+ 145,
      },
      {
        path: '',
        sender: 'Jason blade',
        category: 'transportation',
        date: new Date('2023-06-15'),
        amount:'+'+ 280,
      },
      {
        path: '',
        sender: 'anna',
        category: 'transportation',
        date: new Date('2023-06-15'),
        amount:'+'+ 200,
      },
      {
        path: '',
        sender: 'donia ammar',
        category: 'education',
        date: new Date('2023-06-15'),
        amount:'+'+ 650,
      },
      {
        path: '',
        sender: 'Hany elsaeed',
        category: 'bills',
        date: new Date('2023-06-15'),
        amount:'+'+ 90,
      },
      {
        path: '',
        sender: 'ahmed santa',
        category: 'bills',
        date: new Date('2023-06-15'),
        amount:'+'+ 70,
      },
      {
        path: '',
        sender: 'ahmed amr',
        category: 'bills',
        date: new Date('2023-06-15'),
        amount:'+'+ 660,
      },
    ],
  },
];

 */
